export type {
  ExternalLink,
  Locale,
  LocalizedText,
  RelatedMaterial,
  Work,
  WorkAward,
  WorkEdition,
  WorkLanguage,
  WorkMediaCredits,
  WorkMention,
  WorkRating,
  WorkResearch,
  WorkStatus,
  WorkTranslation,
  WorkType,
} from "@/data/works";
